package com.zed.kz.doskaz.global.service

object Endpoints {

    const val AUTH_FIREBASE = "/api/accessToken/phone"
    const val PROFILE = "/api/profile"
    const val PROFILE_AVATAR = "/api/profile/avatar"
    const val PROFILE_TASKS = "/api/profile/tasks"
    const val PROFILE_OBJECTS = "/api/profile/objects"
    const val PROFILE_COMMENT = "/api/profile/comments"
    const val PROFILE_COMPLAINTS = "/api/profile/complaints"
    const val PROFILE_AWARDS = "/api/profile/awards"
    const val PROFILE_EVENTS = "/api/profile/events"
    const val LIST_CATEGORY = "/api/objects/categories"
    const val CITY_DETECT = "/api/cities/detect"
    const val OBJECT_MAP = "/api/objects/map"
    const val OBJECT_FILTER = "/api/objects/filter"
    const val OBJECT_SEARCH = "/api/objects/search"
    const val OBJECT_BY_ID = "/api/objects/{id}"
    const val OBJECT_VERIFICATION = "/api/objects/{id}/verification/{status}"
    const val OBJECT_REVIEW_CREATE = "/api/objects/{id}/reviews"
    const val FEEDBACK = "/api/feedback"
    const val REGIONAL = "/api/regionalRepresentatives"
    const val BLOG_LIST = "/api/blog/posts"
    const val BLOG = "/api/blog/posts/{id}"
    const val BLOG_COMMENTS = "/api/blog/posts/{id}/comments"
    const val BLOG_CATEGORIES = "/api/blog/categories"
    const val UPLOAD = "/api/storage/upload"
    const val CREATE_OBJECT_VALIDATE = "/api/objects/requests/validate"
    const val CREATE_OBJECT = "/api/objects/requests"
    const val COMPLAINT_OPTIONS = "/api/complaints/type2Attributes"
    const val AUTHORITIES = "/api/complaints/authorities"
    const val CITIES = "/api/cities"
    const val CREATE_COMPLAINT = "/api/complaints"
    const val FORM_ATTRIBUTES = "/api/objects/attributes"
    const val CALC_AVAILABILITY = "/api/objects/calculateZoneScore"
    const val UPLOAD_OBJECT_PHOTOS = "/api/objects/{id}/addPhotos"
    const val AUTH_GOOGLE = "/api/accessToken/google"
    const val AUTH_FACEBOOK = "/api/accessToken/facebook"
    const val AUTH_VK = "/api/accessToken/vk"
    const val AUTH_MAILRU = "/api/accessToken/mailru"
    const val YANDEX_GEOCODE = "https://geocode-maps.yandex.ru/1.x"

    const val DOWNLOAD_FILE = "https://doskaz.vps3.zed.kz/api/complaints/%d/doc?locale=ru"
}